### ISSUE TITLE
Classes disparues

### ISSUE THREAD

**Issue by GuillaumeBertho** [MathieuChailloux/BioDispersal#10]
Bonjour et merci pour les outils mis à disposition !

Habituellement, tout va bien jusqu'à l'étape 5- friction, le processus génère bien une centaine de classes réparties en 17 groupes (étape 3) qui sont ensuite fusionnés en 4 sous trames (étape 4). Le problème est qu'à l'étape 5, il ne propose que les 8 premières classes...

Je dois retourner à l'étape 3 et régénérer les 17 groupes pour qu'ils apparaissent enfin à l'étape 5.
Les groupes existent bien vu que dans le journal j'ai un warning :

[2020-05-08 11:26:52.833537] [warn] Item {'in_layer': 'couches/eau/bdtopo_hydro_surf_hydro.shp', 'mode': 'VField', 'mode_val': 'PERSISTANC', 'group': 'ce_surf'} already exists
[2020-05-08 11:27:15.485639] [warn] Item {'in_layer': 'couches/eau/bdtopo_hydro_plan_eau.shp', 'mode': 'VField', 'mode_val': 'IMPORTANCE', 'group': 'ce_surf'} already exists
[2020-05-08 11:27:48.750844] [warn] Item {'in_layer': 'couches/eau/bdtopo_hydro_tronc_hydro.shp', 'mode': 'VField', 'mode_val': 'LARGEUR', 'group': 'ce_line'} already exists
[2020-05-08 11:28:01.549635] [warn] Item {'in_layer': 'couches/eau/bdtopo_hydro_cours_eau.shp', 'mode': 'VField', 'mode_val': 'IMPORTANCE', 'group': 'ce_line'} already exists
[2020-05-08 11:28:29.479531] [warn] Item {'in_layer': 'couches/zh/zdh_hdf_fus.shp', 'mode': 'VExpr', 'mode_val': ' "code_conf" = 5 or "code_conf" = 4 ', 'group': 'zdh'} already exists
[2020-05-08 11:29:27.786702] [warn] Item {'in_layer': 'couches/hab_synth_trames.shp', 'mode': 'VField', 'mode_val': 'code_cb', 'group': 'os_hab_synth'} already exists
[2020-05-08 11:30:22.557626] [warn] Item {'in_layer': 'couches/cesbio/cesbio2018_hdf_trames.shp', 'mode': 'VField', 'mode_val': 'Classe', 'group': 'os_hab_cesbio'} already exists

**Comment by MathieuChailloux** [comment]
Bonjour,

Je n'ai pas tout bien compris.
Habituellement vous voyez bien la centaine de classes en étape 5 et quelque chose a changé lors de votre dernière utilisation ou bien il y a toujours eu ce problème en étape 5 ?

Si vous pouviez joindre des screenshots ce serait plus parlant pour moi, voire m'envoyer vos données si elles ne sont pas confidentielles (je peux vous envoyer mon adresse mail).

Cordialement,
Mathieu Chailloux

**Comment by GuillaumeBertho** [comment]
Bonjour et désolé pour mes explications peu claires.

J'ai suivi les étapes via le tuto. 
Pas de soucis pour le paramétrage (étape 1) et la définition des sous-trames (étape 2). Lors de la 3e étape j'ai sélectionné 124 classes réparties dans 19 groupes, cf écran ci-dessous :
![Classe disparue 1](https://user-images.githubusercontent.com/65015271/81652076-75decc80-9433-11ea-812c-128382d43a1f.PNG)

Puis je fusionne les rasters précédemment générés (étape 4). Pas de soucis ici non plus.

Les problèmes commencent à l'étape 5 (friction) puisque que je n'ai plus que 74 classes, j'ai donc 50 classes qui ont disparu. 
![SousTrame doublonnées](https://user-images.githubusercontent.com/65015271/81652649-5dbb7d00-9434-11ea-8200-44f6617fb73d.PNG)

Pour régénérer ces 50 classes disparues, je dois retourner à l'étape 3 et refaire la sélection. Alors seulement, les 50 classes disparues sont de nouveau visibles à l'étape 5.
![Classe disparue 2](https://user-images.githubusercontent.com/65015271/81652083-770ff980-9433-11ea-99ed-4fda18d521a7.PNG)


En tentant de reproduire le phénomène pour poster des copies d'écran, je suis confronté à un autre soucis à l'étape 5. Les colonnes des sous-trames ont été dupliquées et les colonnes sont en triples exemplaires (cf copie d'écran ci dessus).

Les données que j'utilise ne sont pas confidentiels mais très volumineuses, chaque rasters fait 2Go environ. Difficile de vous les transmettre dans ces conditions. Je peux vous joindre les xml avant et après l'étape 5 sinon, on voit très bien la disparition des 50 classes.

Cdt,
G.

**Comment by MathieuChailloux** [comment]
Bonjour,

Est-ce que vous avez essayé le bouton 'Recharger les classes' dans l'étape 5 ?
Normalement les classes en étape 5 sont bien sensées être les mêmes qu'en étape 3.
Il est possible qu'il y ait des "trous" dans les codes générés, vous confirmez qu'il vous manque bien certaines classes en étape 5 ?

Pour les colonnes de sous-trame dupliquées, je n'ai jamais vu ce problème, cela arrive dans quelle condition ? En recréant une sélection puis en l'enregistrant ?

Je veux bien vos fichiers XML de configuration pour y voir plus clair.

Cordialement,
Mathieu Chailloux

**Comment by GuillaumeBertho** [comment]
Oui j'ai bien essayé d'utiliser le bouton pour recharger les classes mais j'ai l'impression qu'il ne fait que reprendre celles du xml, or les 50 classes disparues ne sont déjà plus dans le xml. 

Pour les colonnes dupliquées, j'ai réussi à passer outre en fermant QGis et en rechargeant le projet QGis et Biodispersal. Là ça a fonctionné. J'ai pourtant utilisé le même csv à chaque fois.

Entre temps, j'ai mis à jour les plugins, ça doit aider aussi.

J'ai tout de même réussi à aller jusqu'au bout et je vous remercie encore pour ces outils intéressants !

**Comment by MathieuChailloux** [comment]
Effectivement cela peut être dû à une mise à jour car j'avais déjà eu ce problème de synchronisation des classes au début (mais pas les colonnes dupliquées).

Ravi que vous ayez pu aller au bout :-)
