### ISSUE TITLE
Plese add a valid homepage

### ISSUE THREAD

**Issue by pcav** [MathieuChailloux/BioDispersal#2]
this repo could do.
Thanks.

**Comment by MathieuChailloux** [comment]
I've added homepage link in metadatas but no english version of this page is available for now, is it necessary ?

**Comment by pcav** [comment]
This repo could do as well.
Please replace the link.

Thanks.

**Comment by MathieuChailloux** [comment]
Done.

**Comment by pcav** [comment]
Please chack the page on plugins.qgis.org
it apparently needs an update, maybe manually
thanks

**Comment by MathieuChailloux** [comment]
My bad, I was just updating this repo.
I changed the link on QGIS plugins repository.

**Comment by pcav** [comment]
Published, thanks.
