### ISSUE TITLE
BioDispersal is not installing

### ISSUE THREAD

**Issue by vmartinezarias** [MathieuChailloux/BioDispersal#3]
Hello. 
I'm getting this message when I'm trying to install the plugin:
Couldn't load plugin 'BioDispersal' due to an error when calling its initGui() method
AttributeError: module 'progress' has no attribute 'ProgressConnector'

I'm Using QGIS 3-4-3 Madeira, running on Manjaro Linux (an arch-based distro).

Thanks for any help you could bring me.

And thanks for your work.

**Comment by MathieuChailloux** [comment]
Hi,

Thanks for feedback.
This is due to absolute import of a local file (progress.py) that is conflicting with python progress library (that was not installed on my system).
I'm preparing a patch to fix imports as they could be other conflicts.

**Comment by MathieuChailloux** [comment]
New version 1.0.1 is available.
Could you test that installation now works correctly on your system ?

**Comment by vmartinezarias** [comment]
![image](https://user-images.githubusercontent.com/48744766/55249417-02233580-521a-11e9-9be3-28f7459c6c33.png)


Yeah!

Thanks a lot!!!
